version: "3.6"

services:
  api:
    build:
      context: ./server
    working_dir: /go/src/github.com/sawadashota/hcmcafe/server
    volumes:
      - ./server:/go/src/github.com/sawadashota/hcmcafe/server
    ports:
      - 8080:8080
      - 8000:8000
    command: dev_appserver.py ./app/app.yaml --host 0.0.0.0 --admin_host 0.0.0.0 --datastore_path .datastore
  web:
    image: node:10.6.0
    working_dir: /app
    volumes:
      - ./web/:/app
    ports:
      - 3333:3333
    expose:
      - 3333
    links:
      - api
    command: yarn dev
