version: 2
jobs:
  build-web:
    docker:
      - image: node:10.6.0
    working_directory: /go/src/github.com/sawadashota/hcmcafe
    steps:
      - checkout
      - restore_cache:
          keys:
           - yarn-{{ arch }}-{{ .Branch }}-{{ checksum "web/yarn.lock" }}
           - yarn-{{ arch }}-{{ .Branch }}-
           - yarn-{{ arch }}-
      - run:
          name: Install dependencies
          working_directory: web
          command: yarn install
      - save_cache:
          key: yarn-{{ arch }}-{{ .Branch }}-{{ checksum "web/yarn.lock" }}
          paths:
            - ./web/node_modules
      - run:
          name: Build
          working_directory: web
          command: yarn generate
      - persist_to_workspace:
          root: /go/src/github.com/sawadashota/hcmcafe/
          paths:
            - .

  build-go:
    docker:
      - image: circleci/golang:1.10.3
    working_directory: /go/src/github.com/sawadashota/hcmcafe
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          working_directory: server
          command: go get -v -t -d ./...
      - run:
          name: Test
          working_directory: server
          command: go test -v ./...
      - persist_to_workspace:
          root: /go/
          paths:
            - .

  #
  # https://cloud.google.com/sdk/docs/#deb
  #
  deploy:
    docker:
      - image: google/cloud-sdk:206.0.0
    working_directory: /root/go/src/github.com/sawadashota/hcmcafe/server
    steps:
      - attach_workspace:
          at: /root/go/
      - run:
          name: Prepare static files
          command: cp -r ../web/dist app/public
      - run:
          name: Create gcloud service key file
          command: echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
      - run:
          name: Activate gcloud project
          command: gcloud auth activate-service-account --key-file=gcloud-service-key.json
      - deploy:
          command: gcloud app deploy ./app/app.yaml --project $GCLOUD_PROJECT --quiet

workflows:
  version: 2
  default:
    jobs:
      - build-web
      - build-go:
          requires:
            - build-web
      - deploy:
          requires:
            - build-go
          filters:
            branches:
              only: master
