runtime: go
api_version: go1.9

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 5000ms
  max_pending_latency: automatic

handlers:

- url: /api/.*
  script: _go_app
- url: /
  static_dir: public
